### ISSUE TITLE
Error on javdb

### ISSUE THREAD

**Issue by iamrony777** [iamrony777/JavInfo-api#28]
* provider: javdb

error

```text
INFO:     10.220.130.11:0 - "GET /jav/search?code=KSXA-001&provider=all&includeActressUrl=true HTTP/1.1" 500 Internal Server Error
Nov 23 09:22:32 AMERRORERROR:    Exception in ASGI application
Nov 23 09:22:32 AMINFOTraceback (most recent call last):
Nov 23 09:22:32 AMINFO  File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
Nov 23 09:22:32 AMINFO    result = await app(  # type: ignore[func-returns-value]
Nov 23 09:22:32 AMINFO             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 23 09:22:32 AMINFO  File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
Nov 23 09:22:32 AMINFO    return await self.app(scope, receive, send)
Nov 23 09:22:32 AMINFO           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 23 09:22:32 AMINFO  File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1106, in __call__
Nov 23 09:22:32 AMINFO    await super().__call__(scope, receive, send)
Nov 23 09:22:32 AMINFO  File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 122, in __call__
Nov 23 09:22:32 AMINFO    await self.middleware_stack(scope, receive, send)
Nov 23 09:22:32 AMINFO  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 184, in __call__
Nov 23 09:22:32 AMINFO    raise exc
Nov 23 09:22:32 AMINFO  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 162, in __call__
Nov 23 09:22:32 AMINFO    await self.app(scope, receive, _send)
Nov 23 09:22:32 AMINFO  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
Nov 23 09:22:32 AMINFO    raise exc
Nov 23 09:22:32 AMINFO  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
Nov 23 09:22:32 AMINFO    await self.app(scope, receive, sender)
Nov 23 09:22:32 AMINFO  File "/usr/local/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
Nov 23 09:22:32 AMINFO    raise e
Nov 23 09:22:32 AMINFO  File "/usr/local/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
Nov 23 09:22:32 AMINFO    await self.app(scope, receive, send)
Nov 23 09:22:32 AMINFO  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 718, in __call__
Nov 23 09:22:32 AMINFO    await route.handle(scope, receive, send)
Nov 23 09:22:32 AMINFO  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 276, in handle
Nov 23 09:22:32 AMINFO    await self.app(scope, receive, send)
Nov 23 09:22:32 AMINFO  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 66, in app
Nov 23 09:22:32 AMINFO    response = await func(request)
Nov 23 09:22:32 AMINFO               ^^^^^^^^^^^^^^^^^^^
Nov 23 09:22:32 AMINFO  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 274, in app
Nov 23 09:22:32 AMINFO    raw_response = await run_endpoint_function(
Nov 23 09:22:32 AMINFO                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 23 09:22:32 AMINFO  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
Nov 23 09:22:32 AMINFO    return await dependant.call(**values)
Nov 23 09:22:32 AMINFO           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 23 09:22:32 AMINFO  File "/app/src/routes/jav.py", line 68, in search
Nov 23 09:22:32 AMINFO    response = search_all_providers(code, provider, includeActressUrl)
Nov 23 09:22:32 AMINFO               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 23 09:22:32 AMINFO  File "/app/src/__init__.py", line 43, in search_all_providers
Nov 23 09:22:32 AMINFO    result = task.result()
Nov 23 09:22:32 AMINFO             ^^^^^^^^^^^^^
Nov 23 09:22:32 AMINFO  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
Nov 23 09:22:32 AMINFO    return self.__get_result()
Nov 23 09:22:32 AMINFO           ^^^^^^^^^^^^^^^^^^^
Nov 23 09:22:32 AMINFO  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
Nov 23 09:22:32 AMINFO    raise self._exception
Nov 23 09:22:32 AMINFO  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
Nov 23 09:22:32 AMINFO    result = self.fn(*self.args, **self.kwargs)
Nov 23 09:22:32 AMINFO             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 23 09:22:32 AMINFO  File "/app/src/providers/javdb.py", line 140, in search
Nov 23 09:22:32 AMINFO    return self.__getJsonResult(
Nov 23 09:22:32 AMINFO           ^^^^^^^^^^^^^^^^^^^^^
Nov 23 09:22:32 AMINFO  File "/app/src/providers/javdb.py", line 57, in __getJsonResult
Nov 23 09:22:32 AMINFO    _id = page.xpath('//a[@title="Copy ID"]')[0].get('data-clipboard-text')
Nov 23 09:22:32 AMINFO          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
Nov 23 09:22:32 AMINFO  IndexError: list index out of range
```

**Comment by lucius100** [comment]
I never get javdb working, the series are inside javdb site, but the return results always 404

**Comment by iamrony777** [comment]
Damn

There's something wrong in logic, I'll fix in upcoming days

**Comment by lucius100** [comment]
do you have any source to scrape fc2 ppv details ?
I have seen many sites got the movie details for it.

**Comment by iamrony777** [comment]
https://jpmag.net/
